# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: auto-generate-gitbook

on:
    push:
        branches:
            - main

jobs:
    main-to-gh-pages:
        runs-on: ubuntu-latest

        steps:
            - name: checkout main
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: install Node.js
              uses: actions/setup-node@v1

            - name: configure Gitbook
              run: |
                  npm install -g gitbook-cli

            - name: generate _book folder
              run: |
                  gitbook build

            - name: push _book to branch gh-pages
              env:
                  TOKEN: ${{ secrets.TOKEN }}
                  REF: github.com/${{github.repository}}
                  EMAIL: 2023487+Senkita@user.noreply.gitee.com
                  NAME: ${{github.repository_owner}}
              run: |
                  cd _book

                  git config --global user.email "${EMAIL}"
                  git config --global user.name "${NAME}"
                  git init
                  git remote add origin https://${REF}

                  echo -e '# 全栈养成计划\n![auto-generate-gitbook](https://github.com/Senkita/Senkita.github.io/workflows/auto-generate-gitbook/badge.svg)' > README.md

                  git add .
                  git commit -m "build: update by Github Actions with build ${{github.run_number}} of ${{github.workflow}} for Github Pages"
                  git branch -M main
                  git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages
